### PR TITLE
Add in wrapper to eliminate refactoring required right now;

### PR DESCRIPTION
**Pull request by hecon5**
Demo of wrapper for #319 and potential refactoring issues.

### CODE REVIEW

**Comment by joyfullservice** [comment]
I think all the refactoring has already been completed on the `dev` branch... (I don't get any compile issues related to the changes to the performance class.) Would this PR actually be needed in the add-in, or is this more related to your usage of the class in other projects?

**Comment by joyfullservice** [comment]
I think all the refactoring has already been completed on the `dev` branch... (I don't get any compile issues related to the changes to the performance class.) Would this PR actually be needed in the add-in, or is this more related to your usage of the class in other projects?

**Comment by hecon5** [comment]
I missed that when I reviewed `dev`, I'll check my code and see!

**Comment by hecon5** [comment]
Looks like this isn't needed after all! Thanks for the tweaks!

**Pull request closed without merging**
