### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by hecon5**
Revising language on how the addin installation works, and clarified which branch to make PR on. Some of this should / can be simply moved to the Wiki, too.

### CODE REVIEW

**Comment by hecon5** [comment]
Was also going to update the "contributing" pages on the wiki, but appears I can't edit your wiki any longer.

**Comment by joyfullservice** [comment]
Thanks, @hecon5! The challenging part with the wiki is that it is either editable by the world, or only by collaborators. There is no built-in way to support pull requests, which would give me an opportunity to review changes. I am wanting to keep the documentation as clear and professional as possible, so being able to review changes is important to me.

To work around this, I have copied the Wiki docs into the main repository (`master` branch) where they can be edited and PRs can be submitted, just like all the other files. In the future I plan to automate the updating of the actual wiki repository from this folder, but in the mean time I will just copy the changes manually between the repositories.

Feel free to edit the wiki pages in the main project and submit PRs with any proposed changes!  😄

**Comment by hecon5** [comment]
Should we use `dev` or `master`, to ensure that Wiki / documentation stays with where it's relevant?

Examples: with the (now complete) removal of the encryption, we could have edited all the wiki info in the `dev` branch, and it would go live at the same time we removed the function. 

Or, if we add features, the feature documentation would go live simultaneously with the feature implementation.

**Comment by hecon5** [comment]
Also: I did find it odd for a site built on collaboration and review that the wiki has no control. Even Wikipedia has a discussion tool and ability to control edits.

**Comment by joyfullservice** [comment]
> 
> 
> Should we use `dev` or `master`, to ensure that Wiki / documentation stays with where it's relevant?

Great question! Since internally the Wiki for the project is technically its own git repro, ([msaccess-vcs-integration.wiki](https://github.com/joyfullservice/msaccess-vcs-integration.wiki.git)) the menu item link for the project would be tied to the `master` branch on the wiki repro, regardless of which code branch you are on.

I think we should probably plan on (eventually automatically) updating the _project_ wiki from the `master` branch. The `dev` branch can contain updates related to features in development, and those will be merged over to master at the same time as the code changes. You can still browse the `dev` wiki from the files in the `dev` code branch, but you will only see the `master` wiki if you click on the wiki project menu item.

**Comment by hecon5** [comment]
Heh; I think what I read is: 

1. Make changes to the `dev` wiki `.md` files for new feature documentation. These will be merged into `master` when we release new versions.
2. Make changes to `master` & `dev` for non-feature documentation (eg: "How to contribute") (both so that `dev` Wiki files stay inline with `master`). Or, just release new versions more often and only contribute to `dev`...
3. At some point in the future, figure out how to automate the `master>Project Wiki` migration.

**Pull request merged**
