### PR TITLE
Introduce automatic export on save

### PR DESCRIPTION
**Pull request by bclothier**
This PR enables the ability to automatically export any objects upon saving. Some demonstration....

Simple demo of exporting after saving a query via keyboard (Ctrl + S):

https://user-images.githubusercontent.com/2367644/236367400-a5df2a8f-07ab-4e7f-8eeb-757c1904c6ba.mp4

Create 3 queries, rename the query `Query1` to `Query4`, do NOT save the `Query2`, and save `Query3`:

https://user-images.githubusercontent.com/2367644/236367547-c0b210f4-3bde-4d2c-bb7f-09cf893481f8.mp4

Create 2 queries & 2 modules, and handle the "Save" listbox dialog, choosing only 2 out of 4 objects and rename both saved objects:

https://user-images.githubusercontent.com/2367644/236368379-4f0da898-7e87-4b1e-bd6a-264d3d605f08.mp4

For now, this requires manual activation via ribbon:

image

This depends on the [AccessAppHook](https://github.com/bclothier/AccessAppHook) library. I know that one of design goal is to keep everything in VBA as much as possible. Unfortunately, the hook itself is not sustainable as a VBA code due to subclassing and hooking. However, the library itself only reports the objects that were saved and a callback is used so that the addin still can react to the event as if there were an application-level event reporting that object(s) got saved. So there is still some flexibility over how the addin can react to the objects being saved. This is handled via the `modExportOnSave.HandleExportCallback` procedure.

In this initial version, save initiated via mouse clicks or menu are not handled. Keyboard shortcuts such as Ctrl + S, F12 and Shift + F12 are all handled. If any operations trigger a save dialog, that is captured as well (e.g. closing an object that was edited will open a dialog, which is then intercepted). 

It is hoped that with automatic export on save, it will make it easier to be more selective in changes and make it easier to commit only changes. 

I also need to point out that the AccessAppHook is currently a separate repository because I chose to license the code as LGPL as to encourage code-sharing. The library is a standard DLL and could be used for other purposes and for that reason, I wanted to make sure that it is always free and available for others to use or improve, even in their commercial software (which is why it's a LGPL, rather than GPL).

### CODE REVIEW

**Comment by joyfullservice** [comment]
This looks great! I can see how in some workflows people will appreciate having the automatic export when saving database objects. I like that you included the conflict resolution as well. That can be very important, especially when the export is automatically triggered.

Thank you for the efforts to keep the logic and handling of this functionality inside VBA as much as possible. I recognize the limitations (and dangers) of subclassing from VBA, so I think you are taking the right approach to do this through the external DLL. 

The licensing difference is fine and understandable. Just let me know if I should be adding additional notices to the readme or license pages.

Thanks again for your contributions! I can tell that you take time to understand how the system works and do your best to match the coding conventions and styles of the project. Your efforts are much appreciated!  😄

**Comment by joyfullservice** [comment]
FYI, on my machine it crashes Microsoft Access 2010 when I attempt to enable the hook.

Windows 10 Pro 22H2 (19045.2728) (64-bit)
Office 2010 Pro 14.0.7268.5000 (32-bit)

image

**Comment by bclothier** [comment]
Thanks for the report. I'll look into the 32-bit build. 

FYI, a log file is automatically generated for the hook library in the same folder. May be helpful to look at it or post it here.

**Comment by joyfullservice** [comment]
I don't see much in the log... My hunch is that the crash happens while initializing. The following log is from another computer running Windows 11 x64 with the same version of Access 2010 (32-bit).

```
Start: 	2023-05-08 07:39:42
00:00:00.001632	 DEBUG: 	Hook.Initialize                                 	Hook subsystem initalized
00:00:00.005683	 DEBUG: 	Hook.Initialize                                 	  Access main window handle: 180A7C
00:00:00.010488	 DEBUG: 	Hook.Initialize                                 	  Access MDI client handle: 2B0A80
00:00:00.01559	 DEBUG: 	Hook.Initialize                                 	  VBIDE main window handle: 180A7C
00:00:00.020375	 DEBUG: 	Hook.Initialize                                 	  VBIDE MDI client handle: 2B0A80
00:00:00.025178	 DEBUG: 	Hook.Initialize                                 	  Hook module instance: 66C30000
00:00:00.030646	 DEBUG: 	Hook.Initialize                                 	  Process Id: 4EB0
00:00:00.035725	 DEBUG: 	Hook.Initialize                                 	  Thread Id: 970
00:00:00.040564	 DEBUG: 	Hook.Initialize                                 	  After save request delay: 500
```

**Comment by bclothier** [comment]
Just wanted to leave a quick note - I'm looking into this and it looks like though this works on Access O365 64-bit, it doesn't for Access 2010, and I was able to confirm that this isn't to do with 32-bit or 64-bit because I get a crash on 64-bit 2010. Therefore, some more research is needed. My expectation that the windows handling would be the same does not seem to hold even though they look the same from POV of Spy++.

**Pull request merged**
