### PR TITLE
Add trusted location after install

### PR DESCRIPTION
**Pull request by hecon5**
Combined PR for #120.

Only part that's not complete is the timer for how long to wait before just deleting the lock file. 

I've discovered that if Access crashed out, the lock file will stick around for a while; but we also want to ensure that the file's ready to go.

### CODE REVIEW

**Comment by hecon5** [comment]
@joyfullservice this is ready for review; let me know if you have any questions. 

I revised down the wait limits for the addin and lock files so it isn't waiting an inordinate amount of time. I also revised down the wait for the addin file to appear; if it doesn't appear within 3 minutes, it'll just quit. Note that the way the addin opening routine works that it's really not possible to not have it exist, but this should just double check.

**Comment by hecon5** [comment]
Ugh. rebased on the latest changes, and mucked up what branch I wanted to rebase to. Will need to re-rebase again.

**Comment by hecon5** [comment]
Fixed; though, now I am starting to wonder if the lockfile should be cleared during the initial copy; this would allow a prompt to ask the user what to do if it's not deletable (aka: they've got it open in another instance and should close that other Access instance); what say you @joyfullservice ?

**Comment by hecon5** [comment]
Boop @joyfullservice

**Comment by joyfullservice** [comment]
@hecon5 - I like what you have done here. My main hesitation is that for many (perhaps most) developers using the add-in, this will not be an issue. Is there a way we could determine if their current security settings require reopening the database and trusting the file? It seems like that was kind of the point of a [trusted location](https://support.microsoft.com/en-us/office/add-remove-or-change-a-trusted-location-7ee1cdc2-483e-4cbb-bcb3-4e7c67147fb4) in that _every file_ in the location was considered trusted, without needing to add an additional approval for each file.

In your environment, I am wondering if there might be something else going on, like a group policy settings that is removing or changing the trusted location settings, or some other security option that is adding another layer beyond the trusted location exception. My understanding is that if the add-in is in a folder that is considered trusted, it should be able to open and run without _any_ additional security warnings.

To me, what would be really ideal is for the trusted location to only be added/checked when it is determined that it will actually be needed. I am guessing that these other security settings would also be stored in the registry, and perhaps we could check some of those keys before triggering the more invasive security changes and embedded scripts.

Of course if we eventually move towards having our own dedicated installation folder (as part of the ribbon installer), this will be less of an issue since we don't need to worry (as much) about what other files might be lurking in the folder we just trusted. The ([nsis](https://nsis.sourceforge.io/Main_Page)) installer will also be able to determine if Microsoft Access is already running and ensure we don't overwrite a loaded file.

**Comment by hecon5** [comment]
Hmm. I'll ponder this. 

One option that might work is to just open the file and if it runs, you're done. I'll test this and see if it works on my end.

**Comment by hecon5** [comment]
@joyfullservice I revised the launch routines and phrasing to the install routines; it now just always jumps to open the addin file. I've found this works in my environment, even if the trusted location is not saved. I actually think that my instance is ignoring trusted locations, and only trusts files (after some testing with trusted locations and `ACCDE`/`ACCDR` complied files, I strongly suspect this is the case).

I re-arranged the Autorun logic a bit to reduce the number of places a prompt is asked, and instead just used it to revise the message; I know you don't use GoTo much, but in this case, I think it's the best option; let me know what you think.

I also rephrased the `addtrustedlocation` to let users know that they don't need to do it, and to only do it if they have to; and made the `cancel` option button the default.

**Comment by joyfullservice** [comment]
I am kind of leaning towards going ahead with a form to show the options to the user and make it a little more user-friendly during the installation experience. We would still utilize a lot of what you have there, but just present it a different way.

image

How does this strike you?

**Comment by hecon5** [comment]
I like it!

I would suggest the "Open After Install" be defaulted to yes, as users in similar environments to mine won't know that step is required to "trust" the file.

It also takes so little time to actually do (and closes itself afterwards), I think the extra step to the user is minimal, and has only time as a downside.

**Comment by hecon5** [comment]
I just pushed a fix to the `verifyTrustedLocation`; if you click "yes", there's a chance it might be rejected by your registry edit capabilities; so this tests it once again. it also gets rid of the scary message that the addin might not work if you chose "no". 

In the case it was rejected; it tells you, and then gives you an option to try again, if it's trusted, then the check will just move on. This has also the advantage that the return value is correct, instead of just assuming that the writing went well.

I used an `integer` because I've read more than once that some locale settings will have issues with how booleans are interpereted, and boolean values take up an int worth of space anyway [Data type summary](https://docs.microsoft.com/en-us/office/vba/language/reference/user-interface-help/data-type-summary), this doesn't cost anything.

**Comment by joyfullservice** [comment]
I am hoping to push this through before the end of the week. Thanks again for all your work on improving the install process!

**Comment by joyfullservice** [comment]
Merging this now, and I will work on integrating the installer form.

**Pull request merged**
