### PR TITLE
Updating to remove bug from closing form prior to hiding

### PR DESCRIPTION
**Pull request by hecon5**
Fix bug in `clsLblProg` throws errors if you close the form before terminating the class.
Also added in patch to remove unused function `GetParentFormName`.

### CODE REVIEW

**Comment by joyfullservice** [comment]
Thanks, @hecon5! I have actually recently done a pretty significant refactoring of the progress bar class, but haven't actually pushed the changes to the add-in yet... I will see if I can do that soon...  😄

**Comment by hecon5** [comment]
Of course I'd finally get around to this and you'd already done it!

**Comment by joyfullservice** [comment]
> Of course I'd finally get around to this and you'd already done it!

Sorry about that!  🤦‍♂️ Attached is a copy of the updated class... I was still doing some testing with it, but you can check it out and see if it solves the issue.

[clsLblProg.cls.txt](https://github.com/joyfullservice/msaccess-vcs-integration/files/8688978/clsLblProg.cls.txt)

**Comment by joyfullservice** [comment]
FYI, I am also in the process of resolving some dangling object reference issues that had also caused some problems in v4.

For example, you click the ribbon button to export source. This opens the main form and clicks the button to start the export. The log class then attaches to the console text box and progress bar class. The export finishes and the form closes. (Or mostly closes) because the logging class is still holding some object references in the form object. If you try to run an export again, you will get some weird errors because the original form is still hanging out there.

This involves a number of different objects that all interact with each other, and I haven't had a chance to finish this out quite yet, but know that it is in the works.  😄

**Comment by hecon5** [comment]
Finally figured out what was causing the progress bar to get 'stuck' at 100%: `clsLog.Increment` has a `static` value, and in some cases, if the operation you're incrementing is too fast, it'll get stuck and not increment the bar at the end. Then even though you've reset the log and the `ProgressBar` element, it'll immediately load in a full value and then next time will increment above, which sticks it at 100%.

 I think the fix is to move `clsLog.Increment` completely inside `clsLblProg.Increment`, and allow the class to be self-sufficient. That way reset and value settings actually end up doing what you intended, and the outside functions remain wrappers. I'll finish this up shortly and then finalize the PR in a moment.

**Comment by hecon5** [comment]
Ok, I think this is ready; took me a minute to get back to this, had to juggle.

**Comment by hecon5** [comment]
@joyfullservice ok, I'm done now; I went ahead and removed some of the duplicated input variables which were called out in `this.` and a separate variable; those public values shoudl now be set to `this` and a `property` instead which should ensure you don't set one but not the other. Internally and externally they should be the same now.

**Comment by hecon5** [comment]
Some features: 

- Added "Estimated Time remaining" to caption (if set to true); same with estimated completion time; only one or the other can be shown at a time. 
- image
- image


Perhaps a future feature could alternate between them, but since it's so fast typically, that seems a bit silly. 
- Consolidated all variables to `this`
- moved increment tooling completely inside (ok, a few caveats) the `clsLblProg` in `clsLog` to ensure a static variable doesn't stick value at 100% in certain cases.
- Added properties and increment defaults if it's set to zero or less.

**Comment by joyfullservice** [comment]
To keep this from getting too complicated, I think I will go ahead and merge these changes, then make some additional tweaks after the merge, since the PR targets an earlier version of the code base. I will try to add some comments to provide a little context for the things I change...  😄

**Comment by joyfullservice** [comment]
Okay, I have finished some additional modifications and simplifications. I tried to break them out into different commits so you would have some description of why I was making the change, but feel free to add inline comments anywhere that you have further questions or would like to dialog further.  😄 I appreciate your work on this class, and I think it is now better than ever!

**Comment by hecon5** [comment]
Sounds good; I'm going through your commits now and will makes some comments and make a new PR (to keep things tidy).

**Pull request merged**
