### PR TITLE
Wiki update 285

### PR DESCRIPTION
**Pull request by hecon5**
Addresses #285 and also other wiki fixes; hopefully makes readability a lot better with options.

Note: Click on "Rich Diff" to see the changes as displayed on the wiki.

### CODE REVIEW

**Comment by joyfullservice** [comment]
Thanks for taking time to do this! I think it does improve the readability and organization of the information, especially when we are trying to communicate three different related pieces of information for each option. https://developers.google.com/style/tables

**Comment by hecon5** [comment]
Of course; github, and more specifically markdown have some shall we say nuances with tables, so I had to 'cheat' some places, but I hope this works better.

**Comment by hecon5** [comment]
@joyfullservice, ok, I think I'm done tinkering...for now :)

Take a look. I updated the install page as well for a consistent look and term usage. 

One term we may want to consider is the use of **On** and **Off** to describe checkbox states. 
From searching a few KB style guides, I think the more generally accepted state term is **Checked** and **Unchecked** or action/active voice term of **Check** / **Uncheck** (my own internal style guide also states to use Check/Uncheck, too, but since On/Off was used already, I didn't want to change it without discussing first). 

Using Check/Uncheck would also align to the box's type name, too as an added consistency element. 

I've gone ahead and changed it but we can revert (I put all the changes into a single commit for easier rollback) if that's not the desired path.

**Comment by hecon5** [comment]
Maybe even making a style guide page for the Wiki might be a decent idea, too. I'll flesh some out shortly.

**Comment by hecon5** [comment]
Heck, don't I know it. I'll flesh out some more of these and update them. 

I was reading more of [Google's Style Guide](https://developers.google.com/style/), and it appears that even though I was all gung-ho about *Checked/Unchecked*, that using [**Select**](https://developers.google.com/style/word-list#select) and [**Clear**](https://developers.google.com/style/word-list#clear) is a more accurate term anymore. 

I still think *Checked/Unchecked* accurately and correctly describes the **state** of the box, but the **action** should probably be **Select/Clear**. With that in mind, when referring to the **state** use *checked/unchecked*, when referring to the **action** a user performs, use **select/clear**. Wrote up a style guide, cleaning it up a bit.

**Comment by hecon5** [comment]
After reading more, and pondering, holding off on committing the on/off -> true/false change until consensus is made.

**Comment by hecon5** [comment]
Some more thoughts, because I cannot possibly help myself right now.

|Values|Pro|Con
|-|-|-
|**True/False/Null:**|Mirrors the bit-state, is technically correct, and because these are programmers (probably) using the tool, it will make sense. <p>In `code comments` will be more understood. |Harder to parse in plain-language, users not familiar with the boolean type, or that checkboxes are a boolean state may be confused. <p> `True/False/Null` does not accurately describe the actual option state, which is on/off, because an option being on may produce a `False` Result in certain cases <p> **For example:** `Legacy Prompts` On, does not mean prompts are `True`, it means you get a prompt if you have the module AND you've got prompt detection / notification on.
|**On/Off/Null**|Accurately and succinctly describes the option, and whether it is being used or not. <p> Uses plain language accessible by lay people, or users who are using this tool to tweak the UI/UX and may not be familiar with boolean values, especially since Access itself actually uses `yes/no` in their table design for boolean logic columns. | Is inconsistent with generally accepted boolean states, especially when working on comments within the IDE.

Perhaps...there's actually two answers? In Wiki/non-IDE ("`Code`"), use **On/Off/Null**, inside the IDE, use of `True/False/Null` is acceptable as they are the values in use, and ON/Off may not have a 1:1 match with whether a state is `True/False/null` depending on what that option actually is / is doing.

**Comment by hecon5** [comment]
Alright @joyfullservice: I went ahead and just used **On/Off**. I've been stewing on it for the last two weeks, and after all that...I decided that for the lay person, and options screens, **On/Off** is actually more correct, and easier to plain-text prompt. 

I also revised some of the wording instances to be clearer and use more active/imperative voice, as it is also clearer, IMO.

Let me know what you think!

**Comment by hecon5** [comment]
@joyfullservice, I know you're stupid busy but I added in another page to outline how the tool works on a file wise level. Some files may be missing, but I figured having at least a skeleton is better than a ghost.

**Comment by joyfullservice** [comment]
Excellent work, @hecon5! Thank you for all the time and thought you have put into this! It will be a great help to anyone that is just getting familiar with the project.

**Comment by hecon5** [comment]
Thanks! I'm not the most amazing programmer ever, but I do ok on documentation. :)

Excited to see these roll out to the Wiki, and glad to see you're (mostly) caught back up! Being under the steamroller is never a fun place to be!

**Pull request merged**
