### PR TITLE
Adding options for #148 and button.

### PR DESCRIPTION
**Pull request by hecon5**
Adding option to turn off the legacy prompt.

### CODE REVIEW

**Comment by hecon5** [comment]
This apparently is stumping me; I cannot get the `Options.ShowVCSLegacy` to function correctly within a sub, my new option seems to always return true, no matter what I do.

The option is visible, and it does save in the `vcs-options.json` file correctly, but for the life of me I cannot call this correctly apparently. What am I missing? (probably something super obvious).

**Comment by joyfullservice** [comment]
I was noticing something strange going on with the options yesterday... Let me see if I can identify the issue.

**Comment by joyfullservice** [comment]
Found the problem. It is not correctly loading the _project_ options file. Working on a fix for this issue...

**Comment by hecon5** [comment]
I have a suspicion that it may be in `Initialize` of `clsOptions`. At the end of the routine, it loads defaults, instead of loading the saved values (or at least checking if they're there). 

```VBA
...
    ' Load default values
    Me.LoadDefaults
...
```
I wonder if they're falling out of scope somehow (due to a repressed error or just VBA orneryness), and then resetting?

**Comment by hecon5** [comment]
*belay my pondering then! looks like I missed your followup~!

**Review by joyfullservice — APPROVED** [review]
This looks good. Thanks for your work!

**Comment by hecon5** [comment]
Tested and now works! Huzzah

**Pull request merged**
